services:
    aymurai-api:
        image: ghcr.io/aymurai/api:latest
        ports:
            - "8899:8899"
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
            target: aymurai-api
        volumes:
            - ./resources/cache:/resources/cache

    aymurai-api-full:
        image: ghcr.io/aymurai/api:full
        ports:
            - "8899:8899"
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
            target: aymurai-api-full
        restart: always
        deploy:
            resources:
                limits:
                    memory: 4g
                    cpus: "4.0"
