services:
    aymurai-api:
        image: aymurai-api:latest
        container_name: aymurai-api
        ports:
            - "8899:8899"
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
            target: aymurai-api
        env_file:
            - .env
            - .env.common
        volumes:
            - ./resources/cache:/resources/cache

    aymurai-api-full:
        image: aymurai-api:full
        container_name: aymurai-api-prod
        ports:
            - "8899:8899"
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
            target: aymurai-api-full
        restart: always
        deploy:
            resources:
                limits:
                    memory: 4g
                    cpus: "4.0"
