services:
    aymurai-api-dev:
        image: ${API_IMAGE}:dev
        container_name: aymurai-api
        ports:
            - "8899:8899"
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
            target: aymurai-api
        env_file:
            - .env
            - .env.common
        volumes:
            - ./resources/cache:/resources/cache

    aymurai-api-prod:
        image: registry.gitlab.com/collective.ai/datagenero-public/aymurai-api-prod
        container_name: aymurai-api-prod
        ports:
            - "8899:8899"
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
            target: aymurai-api-full
        restart: always
        deploy:
            resources:
                limits:
                    memory: 4g
                    cpus: "4.0"
