# codeblock generated by devtools
# source: /workspace/notebooks/data-preparation/annotations/02-annotations_to_aymurai.ipynb


from copy import deepcopy

from aymurai.meta.types import DataItem
from aymurai.meta.pipeline_interfaces import Transform


class DummyAnnotToPred(Transform):
    """dummy transform to convert annotations into predictions"""

    def __call__(self, item: DataItem) -> DataItem:
        item = deepcopy(item)
        if "annotations" not in item:
            return item
        item["predictions"] = {"entities": item["annotations"]["entities"]}
        return item
