/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeHostRouteImport } from './routes/home/host'
import { Route as HomeFeaturesRouteImport } from './routes/home/features'
import { Route as AppFeatureRouteRouteImport } from './routes/app.$feature/route'
import { Route as AppFeatureIndexRouteImport } from './routes/app.$feature/index'
import { Route as AppFeatureValidationRouteImport } from './routes/app.$feature/validation'
import { Route as AppFeatureProcessRouteImport } from './routes/app.$feature/process'
import { Route as AppFeaturePreviewRouteImport } from './routes/app.$feature/preview'
import { Route as AppFeatureOnboardingRouteImport } from './routes/app.$feature/onboarding'
import { Route as AppFeatureFinishRouteImport } from './routes/app.$feature/finish'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeHostRoute = HomeHostRouteImport.update({
  id: '/home/host',
  path: '/home/host',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeFeaturesRoute = HomeFeaturesRouteImport.update({
  id: '/home/features',
  path: '/home/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFeatureRouteRoute = AppFeatureRouteRouteImport.update({
  id: '/app/$feature',
  path: '/app/$feature',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFeatureIndexRoute = AppFeatureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFeatureRouteRoute,
} as any)
const AppFeatureValidationRoute = AppFeatureValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => AppFeatureRouteRoute,
} as any)
const AppFeatureProcessRoute = AppFeatureProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => AppFeatureRouteRoute,
} as any)
const AppFeaturePreviewRoute = AppFeaturePreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppFeatureRouteRoute,
} as any)
const AppFeatureOnboardingRoute = AppFeatureOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppFeatureRouteRoute,
} as any)
const AppFeatureFinishRoute = AppFeatureFinishRouteImport.update({
  id: '/finish',
  path: '/finish',
  getParentRoute: () => AppFeatureRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/$feature': typeof AppFeatureRouteRouteWithChildren
  '/home/features': typeof HomeFeaturesRoute
  '/home/host': typeof HomeHostRoute
  '/home': typeof HomeIndexRoute
  '/app/$feature/finish': typeof AppFeatureFinishRoute
  '/app/$feature/onboarding': typeof AppFeatureOnboardingRoute
  '/app/$feature/preview': typeof AppFeaturePreviewRoute
  '/app/$feature/process': typeof AppFeatureProcessRoute
  '/app/$feature/validation': typeof AppFeatureValidationRoute
  '/app/$feature/': typeof AppFeatureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home/features': typeof HomeFeaturesRoute
  '/home/host': typeof HomeHostRoute
  '/home': typeof HomeIndexRoute
  '/app/$feature/finish': typeof AppFeatureFinishRoute
  '/app/$feature/onboarding': typeof AppFeatureOnboardingRoute
  '/app/$feature/preview': typeof AppFeaturePreviewRoute
  '/app/$feature/process': typeof AppFeatureProcessRoute
  '/app/$feature/validation': typeof AppFeatureValidationRoute
  '/app/$feature': typeof AppFeatureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/$feature': typeof AppFeatureRouteRouteWithChildren
  '/home/features': typeof HomeFeaturesRoute
  '/home/host': typeof HomeHostRoute
  '/home/': typeof HomeIndexRoute
  '/app/$feature/finish': typeof AppFeatureFinishRoute
  '/app/$feature/onboarding': typeof AppFeatureOnboardingRoute
  '/app/$feature/preview': typeof AppFeaturePreviewRoute
  '/app/$feature/process': typeof AppFeatureProcessRoute
  '/app/$feature/validation': typeof AppFeatureValidationRoute
  '/app/$feature/': typeof AppFeatureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/$feature'
    | '/home/features'
    | '/home/host'
    | '/home'
    | '/app/$feature/finish'
    | '/app/$feature/onboarding'
    | '/app/$feature/preview'
    | '/app/$feature/process'
    | '/app/$feature/validation'
    | '/app/$feature/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home/features'
    | '/home/host'
    | '/home'
    | '/app/$feature/finish'
    | '/app/$feature/onboarding'
    | '/app/$feature/preview'
    | '/app/$feature/process'
    | '/app/$feature/validation'
    | '/app/$feature'
  id:
    | '__root__'
    | '/'
    | '/app/$feature'
    | '/home/features'
    | '/home/host'
    | '/home/'
    | '/app/$feature/finish'
    | '/app/$feature/onboarding'
    | '/app/$feature/preview'
    | '/app/$feature/process'
    | '/app/$feature/validation'
    | '/app/$feature/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppFeatureRouteRoute: typeof AppFeatureRouteRouteWithChildren
  HomeFeaturesRoute: typeof HomeFeaturesRoute
  HomeHostRoute: typeof HomeHostRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/host': {
      id: '/home/host'
      path: '/home/host'
      fullPath: '/home/host'
      preLoaderRoute: typeof HomeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/features': {
      id: '/home/features'
      path: '/home/features'
      fullPath: '/home/features'
      preLoaderRoute: typeof HomeFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$feature': {
      id: '/app/$feature'
      path: '/app/$feature'
      fullPath: '/app/$feature'
      preLoaderRoute: typeof AppFeatureRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$feature/': {
      id: '/app/$feature/'
      path: '/'
      fullPath: '/app/$feature/'
      preLoaderRoute: typeof AppFeatureIndexRouteImport
      parentRoute: typeof AppFeatureRouteRoute
    }
    '/app/$feature/validation': {
      id: '/app/$feature/validation'
      path: '/validation'
      fullPath: '/app/$feature/validation'
      preLoaderRoute: typeof AppFeatureValidationRouteImport
      parentRoute: typeof AppFeatureRouteRoute
    }
    '/app/$feature/process': {
      id: '/app/$feature/process'
      path: '/process'
      fullPath: '/app/$feature/process'
      preLoaderRoute: typeof AppFeatureProcessRouteImport
      parentRoute: typeof AppFeatureRouteRoute
    }
    '/app/$feature/preview': {
      id: '/app/$feature/preview'
      path: '/preview'
      fullPath: '/app/$feature/preview'
      preLoaderRoute: typeof AppFeaturePreviewRouteImport
      parentRoute: typeof AppFeatureRouteRoute
    }
    '/app/$feature/onboarding': {
      id: '/app/$feature/onboarding'
      path: '/onboarding'
      fullPath: '/app/$feature/onboarding'
      preLoaderRoute: typeof AppFeatureOnboardingRouteImport
      parentRoute: typeof AppFeatureRouteRoute
    }
    '/app/$feature/finish': {
      id: '/app/$feature/finish'
      path: '/finish'
      fullPath: '/app/$feature/finish'
      preLoaderRoute: typeof AppFeatureFinishRouteImport
      parentRoute: typeof AppFeatureRouteRoute
    }
  }
}

interface AppFeatureRouteRouteChildren {
  AppFeatureFinishRoute: typeof AppFeatureFinishRoute
  AppFeatureOnboardingRoute: typeof AppFeatureOnboardingRoute
  AppFeaturePreviewRoute: typeof AppFeaturePreviewRoute
  AppFeatureProcessRoute: typeof AppFeatureProcessRoute
  AppFeatureValidationRoute: typeof AppFeatureValidationRoute
  AppFeatureIndexRoute: typeof AppFeatureIndexRoute
}

const AppFeatureRouteRouteChildren: AppFeatureRouteRouteChildren = {
  AppFeatureFinishRoute: AppFeatureFinishRoute,
  AppFeatureOnboardingRoute: AppFeatureOnboardingRoute,
  AppFeaturePreviewRoute: AppFeaturePreviewRoute,
  AppFeatureProcessRoute: AppFeatureProcessRoute,
  AppFeatureValidationRoute: AppFeatureValidationRoute,
  AppFeatureIndexRoute: AppFeatureIndexRoute,
}

const AppFeatureRouteRouteWithChildren = AppFeatureRouteRoute._addFileChildren(
  AppFeatureRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppFeatureRouteRoute: AppFeatureRouteRouteWithChildren,
  HomeFeaturesRoute: HomeFeaturesRoute,
  HomeHostRoute: HomeHostRoute,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
