/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeLayoutRouteRouteImport } from './routes/home._layout/route'
import { Route as AppFeatureRouteRouteImport } from './routes/app.$feature/route'
import { Route as HomeLayoutIndexRouteImport } from './routes/home._layout/index'
import { Route as AppFeatureIndexRouteImport } from './routes/app.$feature/index'
import { Route as HomeLayoutHostRouteImport } from './routes/home._layout/host'
import { Route as HomeLayoutFeaturesRouteImport } from './routes/home._layout/features'
import { Route as AppFeatureValidationRouteImport } from './routes/app.$feature/validation'
import { Route as AppFeatureProcessRouteImport } from './routes/app.$feature/process'
import { Route as AppFeaturePreviewRouteImport } from './routes/app.$feature/preview'
import { Route as AppFeatureOnboardingRouteImport } from './routes/app.$feature/onboarding'
import { Route as AppFeatureFinishRouteImport } from './routes/app.$feature/finish'

const HomeRouteImport = createFileRoute('/home')()

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLayoutRouteRoute = HomeLayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => HomeRoute,
} as any)
const AppFeatureRouteRoute = AppFeatureRouteRouteImport.update({
  id: '/app/$feature',
  path: '/app/$feature',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLayoutIndexRoute = HomeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeLayoutRouteRoute,
} as any)
const AppFeatureIndexRoute = AppFeatureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFeatureRouteRoute,
} as any)
const HomeLayoutHostRoute = HomeLayoutHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => HomeLayoutRouteRoute,
} as any)
const HomeLayoutFeaturesRoute = HomeLayoutFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => HomeLayoutRouteRoute,
} as any)
const AppFeatureValidationRoute = AppFeatureValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => AppFeatureRouteRoute,
} as any)
const AppFeatureProcessRoute = AppFeatureProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => AppFeatureRouteRoute,
} as any)
const AppFeaturePreviewRoute = AppFeaturePreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AppFeatureRouteRoute,
} as any)
const AppFeatureOnboardingRoute = AppFeatureOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppFeatureRouteRoute,
} as any)
const AppFeatureFinishRoute = AppFeatureFinishRouteImport.update({
  id: '/finish',
  path: '/finish',
  getParentRoute: () => AppFeatureRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/$feature': typeof AppFeatureRouteRouteWithChildren
  '/home': typeof HomeLayoutRouteRouteWithChildren
  '/app/$feature/finish': typeof AppFeatureFinishRoute
  '/app/$feature/onboarding': typeof AppFeatureOnboardingRoute
  '/app/$feature/preview': typeof AppFeaturePreviewRoute
  '/app/$feature/process': typeof AppFeatureProcessRoute
  '/app/$feature/validation': typeof AppFeatureValidationRoute
  '/home/features': typeof HomeLayoutFeaturesRoute
  '/home/host': typeof HomeLayoutHostRoute
  '/app/$feature/': typeof AppFeatureIndexRoute
  '/home/': typeof HomeLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeLayoutIndexRoute
  '/app/$feature/finish': typeof AppFeatureFinishRoute
  '/app/$feature/onboarding': typeof AppFeatureOnboardingRoute
  '/app/$feature/preview': typeof AppFeaturePreviewRoute
  '/app/$feature/process': typeof AppFeatureProcessRoute
  '/app/$feature/validation': typeof AppFeatureValidationRoute
  '/home/features': typeof HomeLayoutFeaturesRoute
  '/home/host': typeof HomeLayoutHostRoute
  '/app/$feature': typeof AppFeatureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/$feature': typeof AppFeatureRouteRouteWithChildren
  '/home': typeof HomeRouteWithChildren
  '/home/_layout': typeof HomeLayoutRouteRouteWithChildren
  '/app/$feature/finish': typeof AppFeatureFinishRoute
  '/app/$feature/onboarding': typeof AppFeatureOnboardingRoute
  '/app/$feature/preview': typeof AppFeaturePreviewRoute
  '/app/$feature/process': typeof AppFeatureProcessRoute
  '/app/$feature/validation': typeof AppFeatureValidationRoute
  '/home/_layout/features': typeof HomeLayoutFeaturesRoute
  '/home/_layout/host': typeof HomeLayoutHostRoute
  '/app/$feature/': typeof AppFeatureIndexRoute
  '/home/_layout/': typeof HomeLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/$feature'
    | '/home'
    | '/app/$feature/finish'
    | '/app/$feature/onboarding'
    | '/app/$feature/preview'
    | '/app/$feature/process'
    | '/app/$feature/validation'
    | '/home/features'
    | '/home/host'
    | '/app/$feature/'
    | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/app/$feature/finish'
    | '/app/$feature/onboarding'
    | '/app/$feature/preview'
    | '/app/$feature/process'
    | '/app/$feature/validation'
    | '/home/features'
    | '/home/host'
    | '/app/$feature'
  id:
    | '__root__'
    | '/'
    | '/app/$feature'
    | '/home'
    | '/home/_layout'
    | '/app/$feature/finish'
    | '/app/$feature/onboarding'
    | '/app/$feature/preview'
    | '/app/$feature/process'
    | '/app/$feature/validation'
    | '/home/_layout/features'
    | '/home/_layout/host'
    | '/app/$feature/'
    | '/home/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppFeatureRouteRoute: typeof AppFeatureRouteRouteWithChildren
  HomeRoute: typeof HomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/_layout': {
      id: '/home/_layout'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeLayoutRouteRouteImport
      parentRoute: typeof HomeRoute
    }
    '/app/$feature': {
      id: '/app/$feature'
      path: '/app/$feature'
      fullPath: '/app/$feature'
      preLoaderRoute: typeof AppFeatureRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/_layout/': {
      id: '/home/_layout/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeLayoutIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/app/$feature/': {
      id: '/app/$feature/'
      path: '/'
      fullPath: '/app/$feature/'
      preLoaderRoute: typeof AppFeatureIndexRouteImport
      parentRoute: typeof AppFeatureRouteRoute
    }
    '/home/_layout/host': {
      id: '/home/_layout/host'
      path: '/host'
      fullPath: '/home/host'
      preLoaderRoute: typeof HomeLayoutHostRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/home/_layout/features': {
      id: '/home/_layout/features'
      path: '/features'
      fullPath: '/home/features'
      preLoaderRoute: typeof HomeLayoutFeaturesRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/app/$feature/validation': {
      id: '/app/$feature/validation'
      path: '/validation'
      fullPath: '/app/$feature/validation'
      preLoaderRoute: typeof AppFeatureValidationRouteImport
      parentRoute: typeof AppFeatureRouteRoute
    }
    '/app/$feature/process': {
      id: '/app/$feature/process'
      path: '/process'
      fullPath: '/app/$feature/process'
      preLoaderRoute: typeof AppFeatureProcessRouteImport
      parentRoute: typeof AppFeatureRouteRoute
    }
    '/app/$feature/preview': {
      id: '/app/$feature/preview'
      path: '/preview'
      fullPath: '/app/$feature/preview'
      preLoaderRoute: typeof AppFeaturePreviewRouteImport
      parentRoute: typeof AppFeatureRouteRoute
    }
    '/app/$feature/onboarding': {
      id: '/app/$feature/onboarding'
      path: '/onboarding'
      fullPath: '/app/$feature/onboarding'
      preLoaderRoute: typeof AppFeatureOnboardingRouteImport
      parentRoute: typeof AppFeatureRouteRoute
    }
    '/app/$feature/finish': {
      id: '/app/$feature/finish'
      path: '/finish'
      fullPath: '/app/$feature/finish'
      preLoaderRoute: typeof AppFeatureFinishRouteImport
      parentRoute: typeof AppFeatureRouteRoute
    }
  }
}

interface AppFeatureRouteRouteChildren {
  AppFeatureFinishRoute: typeof AppFeatureFinishRoute
  AppFeatureOnboardingRoute: typeof AppFeatureOnboardingRoute
  AppFeaturePreviewRoute: typeof AppFeaturePreviewRoute
  AppFeatureProcessRoute: typeof AppFeatureProcessRoute
  AppFeatureValidationRoute: typeof AppFeatureValidationRoute
  AppFeatureIndexRoute: typeof AppFeatureIndexRoute
}

const AppFeatureRouteRouteChildren: AppFeatureRouteRouteChildren = {
  AppFeatureFinishRoute: AppFeatureFinishRoute,
  AppFeatureOnboardingRoute: AppFeatureOnboardingRoute,
  AppFeaturePreviewRoute: AppFeaturePreviewRoute,
  AppFeatureProcessRoute: AppFeatureProcessRoute,
  AppFeatureValidationRoute: AppFeatureValidationRoute,
  AppFeatureIndexRoute: AppFeatureIndexRoute,
}

const AppFeatureRouteRouteWithChildren = AppFeatureRouteRoute._addFileChildren(
  AppFeatureRouteRouteChildren,
)

interface HomeLayoutRouteRouteChildren {
  HomeLayoutFeaturesRoute: typeof HomeLayoutFeaturesRoute
  HomeLayoutHostRoute: typeof HomeLayoutHostRoute
  HomeLayoutIndexRoute: typeof HomeLayoutIndexRoute
}

const HomeLayoutRouteRouteChildren: HomeLayoutRouteRouteChildren = {
  HomeLayoutFeaturesRoute: HomeLayoutFeaturesRoute,
  HomeLayoutHostRoute: HomeLayoutHostRoute,
  HomeLayoutIndexRoute: HomeLayoutIndexRoute,
}

const HomeLayoutRouteRouteWithChildren = HomeLayoutRouteRoute._addFileChildren(
  HomeLayoutRouteRouteChildren,
)

interface HomeRouteChildren {
  HomeLayoutRouteRoute: typeof HomeLayoutRouteRouteWithChildren
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeLayoutRouteRoute: HomeLayoutRouteRouteWithChildren,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppFeatureRouteRoute: AppFeatureRouteRouteWithChildren,
  HomeRoute: HomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
