/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeHostRouteImport } from './routes/home/host'
import { Route as HomeFeaturesRouteImport } from './routes/home/features'
import { Route as FeatureValidationRouteImport } from './routes/$feature/validation'
import { Route as FeatureProcessRouteImport } from './routes/$feature/process'
import { Route as FeaturePreviewRouteImport } from './routes/$feature/preview'
import { Route as FeatureOnboardingRouteImport } from './routes/$feature/onboarding'
import { Route as FeatureFinishRouteImport } from './routes/$feature/finish'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeHostRoute = HomeHostRouteImport.update({
  id: '/home/host',
  path: '/home/host',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeFeaturesRoute = HomeFeaturesRouteImport.update({
  id: '/home/features',
  path: '/home/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureValidationRoute = FeatureValidationRouteImport.update({
  id: '/$feature/validation',
  path: '/$feature/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureProcessRoute = FeatureProcessRouteImport.update({
  id: '/$feature/process',
  path: '/$feature/process',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturePreviewRoute = FeaturePreviewRouteImport.update({
  id: '/$feature/preview',
  path: '/$feature/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureOnboardingRoute = FeatureOnboardingRouteImport.update({
  id: '/$feature/onboarding',
  path: '/$feature/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureFinishRoute = FeatureFinishRouteImport.update({
  id: '/$feature/finish',
  path: '/$feature/finish',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$feature/finish': typeof FeatureFinishRoute
  '/$feature/onboarding': typeof FeatureOnboardingRoute
  '/$feature/preview': typeof FeaturePreviewRoute
  '/$feature/process': typeof FeatureProcessRoute
  '/$feature/validation': typeof FeatureValidationRoute
  '/home/features': typeof HomeFeaturesRoute
  '/home/host': typeof HomeHostRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$feature/finish': typeof FeatureFinishRoute
  '/$feature/onboarding': typeof FeatureOnboardingRoute
  '/$feature/preview': typeof FeaturePreviewRoute
  '/$feature/process': typeof FeatureProcessRoute
  '/$feature/validation': typeof FeatureValidationRoute
  '/home/features': typeof HomeFeaturesRoute
  '/home/host': typeof HomeHostRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$feature/finish': typeof FeatureFinishRoute
  '/$feature/onboarding': typeof FeatureOnboardingRoute
  '/$feature/preview': typeof FeaturePreviewRoute
  '/$feature/process': typeof FeatureProcessRoute
  '/$feature/validation': typeof FeatureValidationRoute
  '/home/features': typeof HomeFeaturesRoute
  '/home/host': typeof HomeHostRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$feature/finish'
    | '/$feature/onboarding'
    | '/$feature/preview'
    | '/$feature/process'
    | '/$feature/validation'
    | '/home/features'
    | '/home/host'
    | '/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$feature/finish'
    | '/$feature/onboarding'
    | '/$feature/preview'
    | '/$feature/process'
    | '/$feature/validation'
    | '/home/features'
    | '/home/host'
    | '/home'
  id:
    | '__root__'
    | '/'
    | '/$feature/finish'
    | '/$feature/onboarding'
    | '/$feature/preview'
    | '/$feature/process'
    | '/$feature/validation'
    | '/home/features'
    | '/home/host'
    | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeatureFinishRoute: typeof FeatureFinishRoute
  FeatureOnboardingRoute: typeof FeatureOnboardingRoute
  FeaturePreviewRoute: typeof FeaturePreviewRoute
  FeatureProcessRoute: typeof FeatureProcessRoute
  FeatureValidationRoute: typeof FeatureValidationRoute
  HomeFeaturesRoute: typeof HomeFeaturesRoute
  HomeHostRoute: typeof HomeHostRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/host': {
      id: '/home/host'
      path: '/home/host'
      fullPath: '/home/host'
      preLoaderRoute: typeof HomeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/features': {
      id: '/home/features'
      path: '/home/features'
      fullPath: '/home/features'
      preLoaderRoute: typeof HomeFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$feature/validation': {
      id: '/$feature/validation'
      path: '/$feature/validation'
      fullPath: '/$feature/validation'
      preLoaderRoute: typeof FeatureValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$feature/process': {
      id: '/$feature/process'
      path: '/$feature/process'
      fullPath: '/$feature/process'
      preLoaderRoute: typeof FeatureProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$feature/preview': {
      id: '/$feature/preview'
      path: '/$feature/preview'
      fullPath: '/$feature/preview'
      preLoaderRoute: typeof FeaturePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$feature/onboarding': {
      id: '/$feature/onboarding'
      path: '/$feature/onboarding'
      fullPath: '/$feature/onboarding'
      preLoaderRoute: typeof FeatureOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$feature/finish': {
      id: '/$feature/finish'
      path: '/$feature/finish'
      fullPath: '/$feature/finish'
      preLoaderRoute: typeof FeatureFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeatureFinishRoute: FeatureFinishRoute,
  FeatureOnboardingRoute: FeatureOnboardingRoute,
  FeaturePreviewRoute: FeaturePreviewRoute,
  FeatureProcessRoute: FeatureProcessRoute,
  FeatureValidationRoute: FeatureValidationRoute,
  HomeFeaturesRoute: HomeFeaturesRoute,
  HomeHostRoute: HomeHostRoute,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
