# codeblock generated by devtools
# source: /workspace/notebooks/dev/patterns/02-articles/01-article-matching.ipynb

import spacy

spacy.blank("es")

ART_PREFIX = r"arts?(\.|,)?|ARTÍCULOS?|artículos?"
ART_PREFIX_TITLE = r"SOBRE"

ART_MOD_PREFIX = "incs?[\.,]?|inciso|apartado|(1[\Wo]\s+)?parr"
ART_MOD_CODE = '[\d\w"\)]+'
ART_MOD = f",?\s?(({ART_MOD_PREFIX})(\s({ART_MOD_CODE})))"


ART_CODE = r"\d[\d\.]*(\s?(bis|ter|\w\)))?"
ART_FULL = f"{ART_CODE}({ART_MOD})*"
ART_FULL_MOD = f"{ART_CODE}({ART_MOD})+"


ART_PATTERN_MULTI_NO_PREFIX = r"(?i)\d+(\s?(bis|ter|\d\W\s*parr))"
ART_PATTERN_MULTI_PREFIX = (
    f"(?i)({ART_PREFIX})\s?({ART_FULL})(?:(,|\s(y|\/))? ({ART_FULL}))*"
)
ART_PATTERN_MULTI_PREFIX_TITLE = (
    f"(?i)({ART_PREFIX_TITLE}\s?)({ART_FULL})(?:(,|\s(y|\/))? ({ART_FULL}))*"
)
ART_PATTERN_MULTI_MOD = f"(?i)({ART_FULL_MOD})(?:(,|\s(y|\/))? ({ART_FULL_MOD}))*"


CODES = [
    "Código Contravencional",
    "Código Penal",
    "Código Procesal Penal",
    "Código Penal de la Nación",
    "Constitución Nacional",
    "Código de Transporte",
    "Código Contravencional",
    "Constitución local",
]

ABBRS = [
    "".join(
        [
            token[0]
            for token in code.split(" ")
            if token not in spacy.lang.es.STOP_WORDS and token[0].isupper()
        ]
    )
    for code in CODES
]
ABBRS = filter(lambda x: len(x) > 1, ABBRS)
ABBRS = list(ABBRS)
ABBRS
