# Description: This file contains the colors used in the visualization of the data

colors = {
    "NOMBRE": "orange",
    "GENERO": "orange",
    "NIVEL_INSTRUCCION": "orange",
    "NACIONALIDAD": "orange",
    "FECHA_DE_NACIMIENTO": "orange",
    "EDAD_AL_MOMENTO_DEL_HECHO": "orange",
    "PERSONA_ACUSADA_NO_DETERMINADA": "orange",
    "RELACION_Y_TIPO_ENTRE_ACUSADO/A_Y_DENUNCIANTE": "Magenta",
    "HIJOS_HIJAS_EN_COMUN": "Magenta",
    "FRECUENCIA_EPISODIOS": "Magenta",
    "VIOLENCIA_DE_GENERO": "Coral",
    "MODALIDAD_DE_LA_VIOLENCIA": "Coral",
    "FRASES_AGRESION": "Coral",
    "ART_INFRINGIDO": "brown",
    "CONDUCTA": "red",
    "CONDUCTA_DESCRIPCION": "crimson",
    "DETALLE": "red",
    "OBJETO_DE_LA_RESOLUCION": "red",
    "DECISION": "DarkOrchid",
    "LUGAR_DEL_HECHO": "green",
    "MEDIDAD_DE_PROTECCION_VIGENTES_AL_MOMENTO_DEL_HECHO": "green",
    "FECHA_DEL_HECHO": "green",
    "N_EXPTE_EJE": "DarkOliveGreen",
    "FECHA_RESOLUCION": "DarkOliveGreen",
    "TIPO_DE_RESOLUCION": "DarkOliveGreen",
    "HORA_DE_INICIO": "DarkOliveGreen",
    "HORA_DE_CIERRE": "DarkOliveGreen",
}
