services:
    redis:
        network_mode: host
        image: redis:6.2.6
        container_name: aymurai-redis
        # ports:
        #     - "6379:6379"
        volumes:
            - $PWD/resources/cache/redis:/data

    aymurai-devcontainer-gpu:
        network_mode: host
        image: aymurai-devcontainer-gpu
        container_name: aymurai-devcontainer-gpu
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
            args:
                - CORE_IMAGE_CUDA=registry.gitlab.com/collective.ai/datagenero-public/aymurai-core
                - AYMURAI_EXTRA_PACKAGE=dev,gpu
                - USER_NAME=vscode
                - USER_UID=1000
                - USER_GID=1000
        depends_on:
            - redis
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [ gpu ]
        shm_size: "8gb"
        volumes:
            - ..:/workspace:cached
            - ../notebooks/:/notebooks
            - ../resources/:/resources
            - ../test/:/test
            - $HOME/.ssh/:/home/vscode/.ssh
            - $HOME/.gitconfig:/home/vscode/.gitconfig
            - /var/run/docker.sock:/var/run/docker.sock

        command: /bin/sh -c "while true; do :; done"
        env_file:
            - ../.env.common
            - ../.env

    aymurai-devcontainer:
        network_mode: host
        image: aymurai-devcontainer
        container_name: aymurai-devcontainer-cpu
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
            args:
                - CORE_IMAGE_CUDA=registry.gitlab.com/collective.ai/datagenero-public/aymurai-core
                - AYMURAI_EXTRA_PACKAGE=dev
                - USER_NAME=vscode
                - USER_UID=1000
                - USER_GID=1000
        depends_on:
            - redis
        shm_size: "8gb"
        volumes:
            - ..:/workspace:cached
            - ../notebooks/:/notebooks
            - ../resources/:/resources
            - ../test/:/test
            - $HOME/.ssh/:/home/vscode/.ssh
            - $HOME/.gitconfig:/home/vscode/.gitconfig
            - /var/run/docker.sock:/var/run/docker.sock
        command: /bin/sh -c "while sleep 1000; do :; done"
        env_file:
            - ../.env.common
            - ../.env
