from setuptools import setup, find_packages

setup(
    name="aymurai",
    packages=find_packages(),
    version="0.1.0",
    description="The backend API and machine learning models of AymurAI.",
    author="collective.ai & datagenero.org",
    author_email="aymurai@datagenero.org",
    url="https://github.com/AymurAI/backend",
    install_requires=[
        "more-itertools==10.5.0",
        "odfpy==1.4.1",
        "gdown==4.6.0",
        "joblib==1.4.2",
        "textract==1.6.5",
        "spacy[transformers]==3.4.1",
        "spaczz==0.6.1",
        "datetime_matcher @ git+https://github.com/jedzill4/datetime_matcher",
        "scikit-learn==1.5.2",
        "jiwer==3.0.4",
        "datasets==3.0.0",
        "python-magic==0.4.27",
        "redis==5.0.8",
        "unidecode==1.3.8",
        "sentencepiece==0.2.0",
        "flair @ git+https://github.com/flairNLP/flair@v0.13.1",
        "pytorch-lightning==1.8.3.post1",
        "torchtext==0.13.1",
        # "tensorflow_hub==0.16.1",
        "tensorflow_text>=2.10.0,<2.11.0",
        "fastapi==0.115.0",
        "uvicorn==0.30.6",
        "python-multipart==0.0.10",
        "pydantic==1.9.2",
        "httpx==0.27.2",
        "faker==18.11.2",
        "xmltodict==0.13.0",
        "cachetools==5.3.2",
        "diskcache==5.6.3",
        "mammoth==1.6.0",
        # HOTFIX deprecation issue
        # https://github.com/flairNLP/flair/issues/3441#issuecomment-2039522867
        "scipy<1.13.0",
    ],
    extras_require={
        "": [
            "torch==1.12.1",
            "rich==12.6.0",
        ],
        "gpu": [
            "torch @ https://download.pytorch.org/whl/cu113/torch-1.12.1%2Bcu113-cp310-cp310-linux_x86_64.whl",
            "spacy[cuda113]==3.4.1",
        ],
        "dev": [
            # "rich[jupyter]==12.6.0",
            "tensorboard==2.10.0",
            "jupyterlab==3.4.3",
            "ipywidgets==8.0.1",
            "matplotlib==3.5.2",
            "seaborn==0.11.2",
            "plotly==5.9.0",
        ],
    },
    package_data={"": ["*.yml", "*.yaml", "*.csv"]},
    include_package_data=True,
    scripts=["aymurai/api/main.py"],
    classifiers=["Programming Language :: Python :: 3"],
)
