# codeblock generated by devtools
# source: /workspace/notebooks/dev/patterns/spanish/01-demonyms-pipeline-component.ipynb


from glob import glob

import spacy
import pandas as pd
from spacy.pipeline import EntityRuler

from aymurai.devtools import resolve_package_path

DEMONYMS_BASEPATH = resolve_package_path("aymurai.data.spanish.demonyms")


database = pd.concat(
    [pd.read_csv(path) for path in glob(f"{DEMONYMS_BASEPATH}/*.csv")],
    ignore_index=True,
)
DEMONYMS = database["demonym"].to_list()


@spacy.language.Language.factory("aymurai_norp_ruler")
def es_norp_ruler(nlp, name):
    ruler = EntityRuler(
        nlp,
        patterns=[{"label": "NORP", "pattern": demonym} for demonym in DEMONYMS],
    )
    return ruler
