# codeblock generated by devtools
# source: /workspace/notebooks/dev/patterns/03-sections-spot/31-art-infringido-matcher.ipynb


from copy import deepcopy
from functools import reduce

import regex
from more_itertools import zip_offset

from aymurai.utils.misc import get_element
from aymurai.meta.types import DataItem, DataBlock
from aymurai.meta.pipeline_interfaces import TrainModule


class DummyExtractorArtInfringido(TrainModule):
    def save(self, path: str):
        return

    def load(self, path: str):
        return

    def fit(self, train: DataBlock, val: DataBlock):
        return

    def predict(self, data: DataBlock) -> DataBlock:
        data = [self.predict_single(item) for item in data]

        return data

    def predict_single(self, item: DataItem) -> DataItem:
        item = deepcopy(item)

        # format prediction
        if "predictions" not in item:
            item["predictions"] = {}
        if "records" not in item["predictions"]:
            item["predictions"]["records"] = {}
        if "entities" not in item["predictions"]:
            item["predictions"]["entities"] = []
        if "doc-cats" not in item["predictions"]:
            item["predictions"]["doc-cats"] = {}
        item["predictions"]["records"]["art_infringido"] = []
        item["predictions"]["records"]["conducta"] = []
        item["predictions"]["records"]["codigo_o_ley"] = []

        ents = []
        if "entities" in item["data"]:
            ents += item["data"]["entities"]

        ents = sorted(ents, key=lambda e: e["start"])
        arts = filter(lambda x: x["label"] in ["ART_INFRINGIDO"], ents)
        cond = filter(lambda x: x["label"] in ["CONDUCTA"], ents)
        codi = filter(lambda x: x["label"] in ["CODIGO_O_LEY"], ents)

        # if there is no entities just pass
        if not ents:
            return item

        # records = {}
        # for art, cond, codi in zip_offset(arts, cond, codi, offsets=(0,0,0), longest=True):
        #     records

        item["predictions"]["entities"].append(ents)
        item["predictions"]["records"]["art_infringido"] += list(arts)
        item["predictions"]["records"]["conducta"] += list(cond)
        item["predictions"]["records"]["codigo_o_ley"] += list(codi)

        return item
