# codeblock generated by devtools
# source: /workspace/notebooks/dev/violence-quotes/02-quotes-matching.ipynb

import spacy
import pandas as pd
from spaczz.pipeline import SpaczzRuler
from more_itertools import unique_everseen

from aymurai.devtools import resolve_package_path

QUOTES_BASEPATH = resolve_package_path("aymurai.data.spanish")
QUOTES_FILENAME = f"{QUOTES_BASEPATH}/violence-quotes.csv"

with open(QUOTES_FILENAME, "r") as file:
    QUOTES_DB = map(str.strip, file.readlines())
    QUOTES_DB = list(QUOTES_DB)


def format_pattern(pattern: str) -> dict[str, str]:
    tokens = pattern.split(" ")
    min_r2 = 95 if len(tokens) < 4 else 85
    return {
        "label": "AYMURAI_VIOLENCE_QUOTE",
        "type": "fuzzy",
        "pattern": pattern,
        "kwargs": {"min_r2": min_r2},
    }


@spacy.language.Language.factory("aymurai_violence_quotes_ruler")
def violence_quotes_ruler(nlp, name):
    ruler = SpaczzRuler(nlp, name=name)
    ruler.add_patterns([format_pattern(pattern) for pattern in QUOTES_DB])
    return ruler
