name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*' # Trigger on all tags
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract tag name
        id: envs
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "TAG=${TAG_NAME}" >> $GITHUB_OUTPUT
          if [[ "$TAG_NAME" == *"rc"* ]]; then
            echo "SUFFIX=-rc" >> $GITHUB_OUTPUT
          else
            echo "SUFFIX=" >> $GITHUB_OUTPUT
          fi

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (aymurai-api)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/api/Dockerfile
          push: true
          target: aymurai-api
          build-args: |
            SETUPTOOLS_SCM_PRETEND_VERSION=${{ steps.envs.outputs.TAG }}
          tags: |
            ghcr.io/aymurai/api:latest${{ steps.envs.outputs.SUFFIX }}
            ghcr.io/aymurai/api:${{ github.ref_name }}

      - name: Build and push Docker image (aymurai-api-full)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/api/Dockerfile
          push: true
          target: aymurai-api-full
          build-args: |
            SETUPTOOLS_SCM_PRETEND_VERSION=${{ steps.envs.outputs.TAG }}
          tags: |
            ghcr.io/aymurai/api:full${{ steps.envs.outputs.SUFFIX }}
            ghcr.io/aymurai/api:${{ github.ref_name }}-full
