name: Release

on:
  push:
    branches:
      - feature/gh-actions # Trigger on push to this branch
  pull_request:
    branches:
      - main # Trigger on PR merge to main

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    permissions:
      id-token: write
      contents: write

    steps:

      # Note: we need to checkout the repository at the workflow sha in case during the workflow
      # the branch was updated. To keep PSR working with the configured release branches,
      # we force a checkout of the desired release branch but at the workflow sha HEAD.
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      # - name: Install the project
      #   run: uv sync --all-extras --dev

      - name: Action | Semantic Version Release
        id: release
        # Adjust tag with desired version if applicable.
        uses: python-semantic-release/python-semantic-release@v9.16.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"


      # - name: Install Dependencies
      #   run: |
      #     pip install python-semantic-release setuptools_scm

      # - name: Run Semantic Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: semantic-release publish

      # - name: Force Push Updated Tag (if required)
      #   if: ${{ github.ref_name == 'feature/gh-actions' || github.ref_name == 'main' }}
      #   run: |
      #     latest_tag=$(git describe --tags --abbrev=0)
      #     git tag -f "$latest_tag"
      #     git push origin --tags --force

  sync-dev:
    needs: release
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git User
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"

      - name: Sync Dev Branch
        run: |
          git fetch origin
          git checkout dev
          git merge origin/main --no-edit
          git push origin dev
